# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# gh secret set MAVEN_CENTRAL_USERNAME -a actions --body "<your maven central account username>"
# gh secret set MAVEN_CENTRAL_PASSWORD -a actions --body "<your maven central password>"
# gh secret set SIGNING_KEY -a actions --body "$(gpg --export-secret-keys --armor "<key id>" | grep -v '\-\-' | grep -v '^=.' | tr -d '\n')"
# gh secret set SIGNING_KEY_ID -a actions --body "<your key id>"
# gh secret set SIGNING_KEY_PASSWORD -a actions --body "<your key password>"

name: Deploy to central

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3
# Needed only for Kotlin/Native
#    - uses: actions/cache@v3
#      with:
#        path: |
#          ~/.konan
#        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Publish to Maven Central
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      run: ./gradlew publishToMavenCentral --no-configuration-cache
